version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: tickets-system-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: tickets-system
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - tickets-system-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "80:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - tickets-system-network
    depends_on:
      - postgres

volumes:
  postgres_data:
  pgadmin_data:

networks:
  tickets-system-network:
    driver: bridge
