-- Criação das sequências
CREATE SEQUENCE compra_seq START WITH 1 INCREMENT BY 50;
CREATE SEQUENCE datas_evento_seq START WITH 1 INCREMENT BY 50;
CREATE SEQUENCE item_compra_seq START WITH 1 INCREMENT BY 50;

-- Tabela campo
CREATE TABLE campo (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       modalidade_id BIGINT NOT NULL,
                       campo VARCHAR(255) NOT NULL,
                       descricao_campo VARCHAR(255) NOT NULL
);

-- Tabela cliente
CREATE TABLE cliente (
                         id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         login VARCHAR(100) NOT NULL UNIQUE,
                         email VARCHAR(255) NOT NULL,
                         nome VARCHAR(255) NOT NULL,
                         senha VARCHAR(255) NOT NULL
);

-- Tabela compra
CREATE TABLE compra (
                        id BIGINT NOT NULL PRIMARY KEY,
                        cliente_id BIGINT,
                        data_compra TIMESTAMP(6)
);

-- Tabela datas_evento
CREATE TABLE datas_evento (
                              id BIGINT NOT NULL PRIMARY KEY,
                              data DATE NOT NULL
);

-- Tabela evento
CREATE TABLE evento (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        capacidade_max INTEGER NOT NULL,
                        horario TIME(6) NOT NULL,
                        descricao TEXT,
                        local VARCHAR(255) NOT NULL,
                        nome VARCHAR(255) NOT NULL
);

-- Tabela evento_data_evento
CREATE TABLE evento_data_evento (
                                    datas_evento_id BIGINT NOT NULL,
                                    evento_id BIGINT NOT NULL,
                                    PRIMARY KEY (datas_evento_id, evento_id)
);

-- Tabela evento_organizador
CREATE TABLE evento_organizador (
                                    evento_id BIGINT NOT NULL,
                                    organizador_id BIGINT NOT NULL,
                                    PRIMARY KEY (evento_id, organizador_id)
);

-- Tabela ingressos
CREATE TABLE ingressos (
                           id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           dias INTEGER NOT NULL,
                           cliente BIGINT,
                           evento_id BIGINT NOT NULL,
                           descricao VARCHAR(255)
);

-- Tabela item_compra
CREATE TABLE item_compra (
                             id BIGINT NOT NULL PRIMARY KEY,
                             preco_unitario NUMERIC(38, 2),
                             quantidade INTEGER,
                             compra_id BIGINT NOT NULL,
                             ingresso_id BIGINT NOT NULL
);

-- Tabela modalidade
CREATE TABLE modalidade (
                            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            ingressos_disponiveis INTEGER NOT NULL,
                            preco NUMERIC(38, 2) NOT NULL,
                            ingresso_id BIGINT NOT NULL
);

-- Tabela organizador
CREATE TABLE organizador (
                             id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                             login VARCHAR(100) NOT NULL UNIQUE,
                             email VARCHAR(255) NOT NULL,
                             nome VARCHAR(255) NOT NULL,
                             senha VARCHAR(255) NOT NULL
);

-- Tabela resposta_campo
CREATE TABLE resposta_campo (
                                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                campo_model_id BIGINT NOT NULL,
                                ingresso_model_id BIGINT NOT NULL,
                                resposta TEXT NOT NULL
);

-- Adicionando chaves estrangeiras

ALTER TABLE campo ADD CONSTRAINT fk_campo_modalidade FOREIGN KEY (modalidade_id) REFERENCES modalidade;
ALTER TABLE compra ADD CONSTRAINT fk_compra_cliente FOREIGN KEY (cliente_id) REFERENCES cliente;
ALTER TABLE evento_data_evento ADD CONSTRAINT fk_evento_data_evento FOREIGN KEY (evento_id) REFERENCES datas_evento;
ALTER TABLE evento_data_evento ADD CONSTRAINT fk_data_evento_evento FOREIGN KEY (datas_evento_id) REFERENCES evento;
ALTER TABLE evento_organizador ADD CONSTRAINT fk_evento_organizador FOREIGN KEY (evento_id) REFERENCES organizador;
ALTER TABLE evento_organizador ADD CONSTRAINT fk_organizador_evento FOREIGN KEY (organizador_id) REFERENCES evento;
ALTER TABLE ingressos ADD CONSTRAINT fk_ingressos_cliente FOREIGN KEY (cliente) REFERENCES cliente;
ALTER TABLE ingressos ADD CONSTRAINT fk_ingressos_evento FOREIGN KEY (evento_id) REFERENCES evento;
ALTER TABLE item_compra ADD CONSTRAINT fk_item_compra_compra FOREIGN KEY (compra_id) REFERENCES compra;
ALTER TABLE item_compra ADD CONSTRAINT fk_item_compra_ingresso FOREIGN KEY (ingresso_id) REFERENCES ingressos;
ALTER TABLE modalidade ADD CONSTRAINT fk_modalidade_ingresso FOREIGN KEY (ingresso_id) REFERENCES ingressos;
ALTER TABLE resposta_campo ADD CONSTRAINT fk_resposta_campo FOREIGN KEY (campo_model_id) REFERENCES campo;
ALTER TABLE resposta_campo ADD CONSTRAINT fk_resposta_ingresso FOREIGN KEY (ingresso_model_id) REFERENCES ingressos;

