-- Criação das sequências
CREATE SEQUENCE compra_seq START WITH 1 INCREMENT BY 50;
CREATE SEQUENCE datas_evento_seq START WITH 1 INCREMENT BY 50;
CREATE SEQUENCE item_compra_seq START WITH 1 INCREMENT BY 50;

-- Tabela campo
CREATE TABLE campo (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       modalidade_id BIGINT NOT NULL,
                       campo VARCHAR(255) NOT NULL,
                       descricao_campo VARCHAR(255) NOT NULL
);

-- Tabela cliente
CREATE TABLE cliente (
                         id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         login VARCHAR(100) NOT NULL UNIQUE,
                         email VARCHAR(255) NOT NULL,
                         nome VARCHAR(255) NOT NULL,
                         senha VARCHAR(255) NOT NULL
);

-- Tabela compra
CREATE TABLE compra (
                        id BIGINT NOT NULL PRIMARY KEY,
                        cliente_id BIGINT,
                        data_compra TIMESTAMP(6)
);

-- Tabela datas_evento
CREATE TABLE datas_evento (
                              id BIGINT NOT NULL PRIMARY KEY,
                              data DATE NOT NULL
);

-- Tabela evento
CREATE TABLE evento (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        capacidade_max INTEGER NOT NULL,
                        data DATE NOT NULL,
                        horario TIME(6) NOT NULL,
                        descricao TEXT,
                        local VARCHAR(255) NOT NULL,
                        nome VARCHAR(255) NOT NULL
);

-- Tabela evento_data_evento
CREATE TABLE evento_data_evento (
                                    datas_evento_id BIGINT NOT NULL,
                                    evento_id BIGINT NOT NULL,
                                    PRIMARY KEY (datas_evento_id, evento_id)
);

-- Tabela evento_organizador
CREATE TABLE evento_organizador (
                                    evento_id BIGINT NOT NULL,
                                    organizador_id BIGINT NOT NULL,
                                    PRIMARY KEY (evento_id, organizador_id)
);

-- Tabela ingressos
CREATE TABLE ingressos (
                           id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           dias INTEGER NOT NULL,
                           cliente BIGINT,
                           evento_id BIGINT NOT NULL,
                           descricao VARCHAR(255)
);

-- Tabela item_compra
CREATE TABLE item_compra (
                             id BIGINT NOT NULL PRIMARY KEY,
                             preco_unitario NUMERIC(38, 2),
                             quantidade INTEGER,
                             compra_id BIGINT NOT NULL,
                             ingresso_id BIGINT NOT NULL
);

-- Tabela modalidade
CREATE TABLE modalidade (
                            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            ingressos_disponiveis INTEGER NOT NULL,
                            preco NUMERIC(38, 2) NOT NULL,
                            ingresso_id BIGINT NOT NULL
);

-- Tabela organizador
CREATE TABLE organizador (
                             id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                             login VARCHAR(100) NOT NULL UNIQUE,
                             email VARCHAR(255) NOT NULL,
                             nome VARCHAR(255) NOT NULL,
                             senha VARCHAR(255) NOT NULL
);

-- Tabela resposta_campo
CREATE TABLE resposta_campo (
                                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                campo_model_id BIGINT NOT NULL,
                                ingresso_model_id BIGINT NOT NULL,
                                resposta TEXT NOT NULL
);

-- Adicionando chaves estrangeiras
ALTER TABLE campo ADD CONSTRAINT FKa8n54q096cq9sdw649lx6ssxl FOREIGN KEY (modalidade_id) REFERENCES modalidade;
ALTER TABLE compra ADD CONSTRAINT FKni21w35sfgo033m8l93ki11ab FOREIGN KEY (cliente_id) REFERENCES cliente;
ALTER TABLE evento_data_evento ADD CONSTRAINT FK3v30g1hv19v22g7xkffs2k2l5 FOREIGN KEY (evento_id) REFERENCES datas_evento;
ALTER TABLE evento_data_evento ADD CONSTRAINT FKj11skd4g3e2nowl47vq69q4eh FOREIGN KEY (datas_evento_id) REFERENCES evento;
ALTER TABLE evento_organizador ADD CONSTRAINT FKf60bdbd74s1udgkx3unkbj3m4 FOREIGN KEY (evento_id) REFERENCES organizador;
ALTER TABLE evento_organizador ADD CONSTRAINT FK87o29k7d0bu94l4sl9n4ykujs FOREIGN KEY (organizador_id) REFERENCES evento;
ALTER TABLE ingressos ADD CONSTRAINT FKtgph8tw2ri5ot8fbqnrlwgsj5 FOREIGN KEY (cliente) REFERENCES cliente;
ALTER TABLE ingressos ADD CONSTRAINT FKl3c95uac4ffto02mxxxuclklw FOREIGN KEY (evento_id) REFERENCES evento;
ALTER TABLE item_compra ADD CONSTRAINT FKovscx99wpxanu7sytiqarv700 FOREIGN KEY (compra_id) REFERENCES compra;
ALTER TABLE item_compra ADD CONSTRAINT FKnytn0btpacuteooecelitrco1 FOREIGN KEY (ingresso_id) REFERENCES ingressos;
ALTER TABLE modalidade ADD CONSTRAINT FKspyefcq1yj12uuodi2wfpu5yt FOREIGN KEY (ingresso_id) REFERENCES ingressos;
ALTER TABLE resposta_campo ADD CONSTRAINT FKroea5eyc039mvnt82gwtmn7b3 FOREIGN KEY (campo_model_id) REFERENCES campo;
ALTER TABLE resposta_campo ADD CONSTRAINT FK60ecfcrm7rr6r82y44kf273f0 FOREIGN KEY (ingresso_model_id) REFERENCES ingressos;